---
## /* vim: set tabstop=2 softtabstop=2 shiftwidth=2 expandtab smarttab autoindent: */

- name: 'Converge'
  hosts: 'all'
  become: true

  pre_tasks:
  - name: 'Make sure the package cache is up to date'
    ansible.builtin.apt:
      update_cache: true
    when:
    - "ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'"
    changed_when: false

  roles:
  - role: 'mireiawen.utils'
